concretesolutions/cesta-basica

backend/.env.example, backend/package.json, backend/src/core/database.js, backend/src/core/router.js, backend/src/repositories/user.js, backend/src/rules/index.js, backend/src/rules/sign-in.js, backend/src/rules/sign-up.js, backend/yarn.lock
Criando rotas de sign-in e sign-up
*IMPORTANTE*
A rota de sign-up não faz parte do mvp, mas será útil durante o desenvolvimento
=> add sign-in and sign-up

backend/src/middlewares/auth-required.js, backend/src/middlewares/index.js, backend/src/middlewares/role-required.js, backend/src/rules/sign-in.js
No arquivo de rota importe os middlewares (se já não estiver importado)
```javascript
import { authRequired, roleRequired } from '../middlewares'
```
Adicione o middleware antes do handler da sua sua rota
```javascript
router.post('/private', authRequired, (req, res) =>{
// seu código aqui
})
```
Ao usar o middleware `authRequired` sua request vai ter acesso ao objeto `auth`  com a estrutura abaixo
```javascript
{
id: String,
login: String,
role: String
}
```
O middleware `roleRequired ` só funciona em rotas autenticadas e requer que informe para qual role é essa rota, por exemplo
```javascript
router.post('/private', authRequired, roleRequired('admin'), (req, res) =>{
// seu código aqui
})
```
=> add auth middlewares

backend/src/middlewares/auth-required.js, backend/src/middlewares/index.js, backend/src/middlewares/role-required.js
No arquivo de rota importe os middlewares (se já não estiver importado)
```javascript
import { authRequired } from '../middlewares'
```
Adicione o middleware antes do handler da sua sua rota
```javascript
router.post('/private', authRequired(), (req, res) =>{
// seu código aqui
})
```
Ao usar o middleware `authRequired` sua request vai ter acesso ao objeto `auth`  com a estrutura abaixo
```javascript
{
id: String,
login: String,
role: String
}
```
O middleware `authRequired`  pode receber uma `string` com a `role` do usuário
```javascript
router.post('/private', authRequired('admin'), (req, res) =>{
// seu código aqui
})
```
=> code review: combine auth and role in just one middleware

backend/src/repositories/user.js
=> fix user model role

backend/package.json, backend/src/repositories/donation.js, backend/src/rules/index.js, backend/yarn.lock
Corri alguns erros que impediam o startup da aplicação
=> fix erros to startup application

backend/src/core/router.js, backend/src/rules/list-donations.js
=> listar doações do líder

frontend/.gitignore, frontend/src/components/Button/Button.scss, frontend/src/components/Input/InputTypes.js, frontend/src/components/RadioButton/RadioButton.js, frontend/src/components/RadioButton/index.js, frontend/src/pages/DonationProf/DonationProf.js, frontend/src/pages/DonationProf/DonationProf.scss, frontend/src/pages/Login/Login.js, frontend/src/utils/strings.js
Corrigindo tamanho de botão.
Adicionando funcionalidade de mostrar nota fiscal.
=> feat/fix: button size and improving taxes ticket

frontend/src/components/Button/Button.scss, frontend/src/components/Paragraph/Paragraph.js, frontend/src/components/Paragraph/Paragraph.scss, frontend/src/components/SubTitle/SubTitle.scss, frontend/src/components/Terms/Terms.js, frontend/src/components/Title/Title.js, frontend/src/components/Title/Title.scss, frontend/src/pages/Terms/Term.scss, frontend/src/pages/Terms/Terms.js, frontend/src/services/handles.js, frontend/src/utils/strings.js
atualizado textos, espaçamentos e integração e adição de font
=> fix: adjust visual and integration

frontend/src/components/Legend/Legend.scss, frontend/src/components/Link/Link.scss, frontend/src/components/SubTitle/SubTitle.scss, frontend/src/components/Title/Title.scss, frontend/src/pages/Checklist/Checklist.scss
Fix fonts and and some broken components
=> fix: fonts broken revision

frontend/public/index.html, frontend/public/manifest.json, frontend/src/components/Button/Button.scss, frontend/src/components/Items/Items.js, frontend/src/components/Legend/Legend.js, frontend/src/components/Legend/Legend.scss, frontend/src/components/Terms/Terms.js, frontend/src/components/Terms/Terms.scss, frontend/src/pages/Donation/Donation.js, frontend/src/pages/Donation/Donation.scss, frontend/src/pages/DonationList/DonationItem/DonationItem.js, frontend/src/pages/DonationList/DonationList.js, frontend/src/pages/DonationProf/DonationProf.scss, frontend/src/pages/Modal/Modal.js, frontend/src/pages/Modal/Modal.scss, frontend/src/pages/Received/Received.js, frontend/src/pages/Received/Received.scss, frontend/src/pages/ReceivedCurrent/ReceivedCurrent.js, frontend/src/pages/ReceivedCurrent/ReceivedCurrent.scss, frontend/src/pages/ReceivedCurrentProf/ReceivedCurrentProf.scss, frontend/src/pages/Terms/Term.scss, frontend/src/store/index.js
Para ciência. 
Ajustes de componentes e telas.
=> Fix: adjusts and adjusts

frontend/src/pages/DonationList/DonationList.js, frontend/src/pages/Terms/Terms.js
Caso o usuário tenha permitido o uso de geolocation, é necessário pedir novamente se ele saiu e entrou. Isso é para o envio de imagem.
=> fix: persist geolocation

frontend/src/pages/ReceivedCurrentProf/ReceivedCurrentProf.js
=> aply validation in  buttonn

frontend/public/index.html, frontend/src/pages/DonationProf/DonationProf.js, frontend/src/pages/Received/Received.js, frontend/src/pages/ReceivedCurrent/ReceivedCurrent.js, frontend/src/pages/ReceivedCurrentProf/ReceivedCurrentProf.js, frontend/src/services/analytics.js, frontend/src/utils/strings.js
- Adição do script base do google tag manager
- Criação de camada de serviço para abstrair as chamadas ao google tag manager
- Implementação de eventos para as adições principais
=> Implementação do Google Analytics via Google Tag Manager

frontend/src/components/Input/Input.js, frontend/src/components/Input/Input.scss, frontend/src/pages/DonationList/DonationList.js, frontend/src/pages/DonationProf/DonationProf.js, frontend/src/pages/Login/Login.js, frontend/src/utils/strings.js
Estoria:
https://trello.com/c/KlwRllop
https://trello.com/c/KlwRllop -> parte do login
como ficou:
como era:
Atualizar Titulo do card list para donationID
Como Ficou:
=> done adjust in input

frontend/src/routes/routeWrapper.js, frontend/src/services/analytics.js
Enviando id de usuário e role para o google analytics para criar dimenções personalizadas de segmentação
=> add user role and id on datalayer for custom dimension

frontend/src/pages/DonationList/DonationList.js, frontend/src/store/index.js
Hook estava se auto chamando causando erro no router.
=> fix: hooks call auto

backend/src/core/router.js
Corrigindo para status retornam 200 e não 404.
=> fix: returning status 200

frontend/src/components/File/File.js, frontend/src/components/File/File.scss, frontend/src/pages/DonationProf/DonationProf.js, frontend/src/pages/DonationProf/DonationProf.scss, frontend/src/utils/strings.js
Estória: Tela 02 - Evidencia Recebimento Vazia
https://trello.com/c/T61UM5sC/93-ajustes-nos-layout
=> fix: Change texts on DonationProf

frontend/src/components/Items/Items.js, frontend/src/components/Items/Items.scss, frontend/src/components/Loader/Loader.scss, frontend/src/pages/ReceivedCurrent/ReceivedCurrent.js, frontend/src/pages/ReceivedCurrent/ReceivedCurrent.scss
Alterar regra dos cartões - Enquanto o primeiro cartão da lista não estiver sido moderado, os de baixo não podem ser editados.
Estória (Tela 05 e 09) - https://trello.com/c/T61UM5sC/93-ajustes-nos-layout
=> feat: improving when select option to moderate

frontend/src/services/API/donationList.js, frontend/src/services/API/upload.js, frontend/src/utils/compressFile.js
Rotina para comprimir arquivo usando canvas.
=> feat: compress image files

frontend/src/pages/Modal/Modal.js, frontend/src/pages/Modal/Modal.scss
Refatoração do botão close, ajustes na modal e estilos também
Estória(Tela 10): https://trello.com/c/T61UM5sC/93-ajustes-nos-layout
**Alteração:**
**Antigo:**
=> fix: donation modal close btn refactoring and + adjustments

backend/src/load-data/load-types/user.js, backend/src/repositories/user.js
Sempre salvar senhas apenas com criptografia!
=> remove insecurity data

frontend/src/services/API/donationList.js
Correção do loading infinito na tela de detalhes da doação (DonationDetails)
=> fix: Adjust on DonationDetails service

frontend/src/pages/DonationList/DonationList.js
removendo botão caso não seja admin
=> fix: remove button if not is admin

frontend/src/pages/DeliveredDetail/Delivered/Delivered.js, frontend/src/pages/DeliveredDetail/DeliveredDetail.js, frontend/src/pages/ReceivedCurrentProf/ReceivedCurrentProf.js, frontend/src/services/API/donationList.js, frontend/src/utils/strings.js
=> feature: add field of number

frontend/src/components/Input/InputTypes.js, frontend/src/pages/UpdateEmail/UpdateEmail.js, frontend/src/pages/UpdateEmail/index.js, frontend/src/pages/UpdateEmail/style.scss, frontend/src/routes/index.js, frontend/src/services/API/updateDataUser.js, frontend/src/utils/strings.js
estoria: 
https://trello.com/c/SnZErUDY
caminho: 
login: 13523491673
senha: 12345678
path = http://localhost:3000/profile/update-email
Esquerda(como deveria ficar) / Direita(como ficou) -> input vazio
Esquerda(como deveria ficar) / Direita(como ficou) -> input preenchido
=> feature: page of update email

frontend/src/pages/Charge/Charge/Charge.js
- Correção de erros de imports em `./src/pages/Charge/Charge/Charge.js`
=> fix: imports errors in charge page

frontend/src/utils/strings.js
Atualizadas mensagens de feedback de senha
=> fix: update string of feedback in update password

frontend/src/pages/Charge/ChargeList/ChargeList.js, frontend/src/pages/Charge/ChargeList/CommonComponents/ChargeItem/ChargeItem.js, frontend/src/pages/Charge/ChargeList/CommonComponents/ChargeItem/ChargeItem.scss
Estória: https://trello.com/c/hEdMQZhV/167-tela-de-cargas-review
Alterações:
- Mostrar status de processamento da Carga
- Ajuste de css
Resultado:
=> fix: adjust in ChargeList component and css

backend/src/core/router.js, backend/src/rules/report.js, lambdas/cesta-basica-report-factory/app.js
Registrar o nome do usuário que solicitou a criação do report
=> Refactor: add campo value na criação do report

frontend/src/pages/Export/ReportList/ReportItem/index.js, frontend/src/pages/Export/ReportList/ReportItem/style.scss, frontend/src/pages/Export/ReportList/ReportList.js
Estória: Solicitado por Eldo Lucas (08.05.2020)
Lista de Exportação:
- Adicionado label com o nome da pessoa que gerou o relatório.
- Adicionado label com o horário em que o relatório foi gerado.
Resultado:
=> feature: add field owner and creation hour

backend/.env.example, backend/package-lock.json, backend/package.json, backend/src/services/encrypt.js, backend/yarn.lock, frontend/package-lock.json, frontend/package.json, frontend/yarn.lock
Esse PR implementa:
- Atualização de dependências (frontend e backend)
- Atualização de arquivo env.example
- Ajuste em arquivo encrypt.js
=> implements updating application dependencies and adjust in env.example  and encrypt.js

package-lock.json, yarn.lock
PR para atualização de package-lock.json e yarn-lock.json que se encontram na raiz do projeto
=> implements new dependencies update

backend/src/services/s3.js
Esse PR implementa:
- ajuste em serviço de acesso para s3 passando as credencias via construtor
=> Implements adjust in service s3 to accept access key and secret key

backend/package.json, backend/src/rules/bulk-insertion/donation/filter.js, backend/src/rules/bulk-insertion/site/filter.js, backend/src/rules/bulk-insertion/transfer/filter.js, backend/src/rules/bulk-insertion/user/filter.js, backend/src/rules/bulk-insertion/voucher/filter.js, backend/src/utils/index.js, backend/src/utils/normalizeLines.js
Esse PR implementa:
- correção no módulo filter (bulk-insertion/filter/[donation, site, user, transfer, voucher])
- criação da pasta utils
-  criação do módulo normalizeLines para normalizar as linhas do csv
- remoção de aws-ric e post-install de package.json
=> implements fix in bulk insertion filter with normalize line function

backend/.env.example, backend/config/index.js, backend/src/services/s3.js
Ajuste em ACL do bucket (passando permissão no construtor do método upload)
=> Implementa ACL(permission) em metodo de upload para o s3
